from unittest.mock import AsyncMock, patch
import pytest
import httpx
from app.main import app
from app.agent.model_router import ModelRouter, RoutingMode, RoutingDecision
from app.agent.openrouter_client import OpenRouterClient
from app.agent.orchestrator import AgentOrchestrator


# --- Unit Tests for ModelRouter ---

def test_router_normal_mode_default():
    router = ModelRouter(default_mode="auto", ollama_model="qwen3.5:9b", openrouter_heavy_model="heavy-model")
    decision = router.evaluate("What is the weather like today?")
    assert decision.mode == "normal"
    assert decision.provider == "ollama"
    assert decision.model == "qwen3.5:9b"


def test_router_explicit_heavy_mode():
    router = ModelRouter(default_mode="auto", ollama_model="qwen3.5:9b", openrouter_heavy_model="heavy-model")
    decision = router.evaluate("Hello", requested_mode="heavy")
    assert decision.mode == "heavy"
    assert decision.provider == "openrouter"
    assert decision.model == "heavy-model"


def test_router_explicit_normal_mode():
    router = ModelRouter(default_mode="auto", ollama_model="qwen3.5:9b", openrouter_heavy_model="heavy-model")
    decision = router.evaluate("Design a distributed system architecture", requested_mode="normal")
    assert decision.mode == "normal"
    assert decision.provider == "ollama"


def test_router_heavy_tag_trigger():
    router = ModelRouter(default_mode="auto", ollama_model="qwen3.5:9b", openrouter_heavy_model="heavy-model")
    decision = router.evaluate("[heavy] please explain this complex quantum equation.")
    assert decision.mode == "heavy"
    assert decision.provider == "openrouter"


def test_router_heavy_task_pattern():
    router = ModelRouter(default_mode="auto", ollama_model="qwen3.5:9b", openrouter_heavy_model="heavy-model")
    decision = router.evaluate("Help me create a system design for a high-availability microservice architecture.")
    assert decision.mode == "heavy"
    assert decision.provider == "openrouter"


def test_router_custom_model_override():
    router = ModelRouter(default_mode="auto", ollama_model="qwen3.5:9b", openrouter_heavy_model="heavy-model")
    decision = router.evaluate("Hello", requested_mode="heavy", requested_model="custom/model-x")
    assert decision.model == "custom/model-x"


def test_openrouter_client_unconfigured_error():
    client = OpenRouterClient(api_key=None)
    assert client.is_configured is False
    with pytest.raises(ValueError, match="OPENROUTER_API_KEY is not configured"):
        import asyncio
        asyncio.run(client.chat(messages=[], model="test"))


# --- Integration Tests with FastAPI app ---

@pytest.mark.anyio
async def test_chat_normal_mode_local_isolation():
    """Verify that a Normal Mode request runs purely via Ollama with provider='ollama'."""
    payload = {
        "message": "Hello, answer with 'TEST_OK'",
        "mode": "normal",
        "model": "qwen2.5:0.5b"
    }
    async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://test", timeout=30.0) as ac:
        response = await ac.post("/chat", json=payload)
    
    assert response.status_code == 200
    data = response.json()
    assert data["provider"] == "ollama"
    assert data["fallback_used"] is False
    assert len(data["response"]) > 0


@pytest.mark.anyio
async def test_chat_heavy_mode_mocked_success():
    """Verify Heavy Mode dispatch to OpenRouter."""
    mock_openrouter_response = {
        "choices": [
            {
                "message": {
                    "role": "assistant",
                    "content": "This is a detailed heavy reasoning response generated by OpenRouter."
                }
            }
        ]
    }

    with patch.object(OpenRouterClient, "chat", new_callable=AsyncMock) as mock_chat:
        mock_chat.return_value = mock_openrouter_response

        payload = {
            "message": "Architect a fault-tolerant distributed consensus engine.",
            "mode": "heavy"
        }
        async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://test", timeout=30.0) as ac:
            response = await ac.post("/chat", json=payload)
        
        assert response.status_code == 200
        data = response.json()
        assert data["provider"] == "openrouter"
        assert "OpenRouter" in data["response"]
        assert data["fallback_used"] is False
        mock_chat.assert_awaited_once()


@pytest.mark.anyio
async def test_chat_heavy_mode_fallback_on_error():
    """Verify graceful fallback to local Ollama if OpenRouter returns rate-limit or network failure."""
    with patch.object(OpenRouterClient, "chat", new_callable=AsyncMock) as mock_chat:
        mock_chat.side_effect = RuntimeError("OpenRouter rate limit reached (HTTP 429).")

        payload = {
            "message": "Explain recursion in one sentence.",
            "mode": "heavy",
            "model": "qwen2.5:0.5b"
        }
        async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://test", timeout=30.0) as ac:
            response = await ac.post("/chat", json=payload)
        
        assert response.status_code == 200
        data = response.json()
        # Fallback executed on local Ollama
        assert data["provider"] == "ollama"
        assert data["fallback_used"] is True
        assert "Fallback: OpenRouter failed" in data["route_reason"]
        assert len(data["response"]) > 0
