"""
Status briefings.

A briefing is deterministic — assembled from the snapshot, not generated by
the model. That keeps it instant, always available (even with the model
evicted), and impossible to hallucinate numbers into.
"""
from __future__ import annotations

import time
from datetime import datetime
from typing import Any, Optional

from app.awareness.observations import Observation, SystemSnapshot


def address_suffix(persona: Any) -> str:
    """', sir' for personas that use an address term, '' for those that don't."""
    term = (getattr(persona, "address_term", "") or "").strip()
    return f", {term}" if term else ""


def format_spoken(observation: Observation, persona: Any) -> str:
    """Render an observation's spoken line in the active persona's voice."""
    text = observation.spoken or observation.detail or observation.title
    return text.replace("{address}", address_suffix(persona))


def time_of_day_greeting(now: Optional[float] = None) -> str:
    hour = datetime.fromtimestamp(now or time.time()).hour
    if hour < 12:
        return "Good morning"
    if hour < 18:
        return "Good afternoon"
    return "Good evening"


def _gb(mb: float) -> float:
    return round(mb / 1024.0, 1)


def build_briefing(
    snapshot: SystemSnapshot,
    persona: Any,
    active_conditions: Optional[list[str]] = None,
    now: Optional[float] = None,
) -> dict[str, str]:
    """
    Compose a status briefing as both screen text (markdown) and spoken text.
    """
    address = address_suffix(persona)
    greeting = f"{time_of_day_greeting(now)}{address}."
    conditions = active_conditions or []

    lines: list[str] = []
    spoken: list[str] = [greeting]

    if snapshot.gpu_available and snapshot.vram_total_mb > 0:
        used, total = _gb(snapshot.vram_used_mb), _gb(snapshot.vram_total_mb)
        lines.append(
            f"- **GPU** {snapshot.gpu_name or 'unknown'} — "
            f"{snapshot.gpu_util_percent:.0f}% load, VRAM {used} / {total} GB"
            + (f", {snapshot.gpu_temp_c:.0f}°C" if snapshot.gpu_temp_c is not None else "")
        )
        spoken.append(
            f"The GPU is at {snapshot.gpu_util_percent:.0f} percent "
            f"with {used} of {total} gigabytes of VRAM in use."
        )
    else:
        lines.append("- **GPU** not detected — running on CPU")
        spoken.append("No GPU is detected; inference is on the CPU.")

    if snapshot.ram_total_mb > 0:
        lines.append(
            f"- **Memory** {_gb(snapshot.ram_used_mb)} / {_gb(snapshot.ram_total_mb)} GB "
            f"({snapshot.ram_percent:.0f}%)"
        )
        spoken.append(f"System memory is at {snapshot.ram_percent:.0f} percent.")

    if snapshot.disk_total_gb > 0:
        lines.append(f"- **Disk** {snapshot.disk_free_gb:.0f} GB free")
        spoken.append(f"There are {snapshot.disk_free_gb:.0f} gigabytes free on disk.")

    if snapshot.battery_percent is not None:
        power = "on mains" if snapshot.battery_plugged else "on battery"
        lines.append(f"- **Power** {snapshot.battery_percent:.0f}% ({power})")
        if not snapshot.battery_plugged:
            spoken.append(f"You are on battery at {snapshot.battery_percent:.0f} percent.")

    lines.append(
        f"- **Governor** {snapshot.governor_status}"
        + (" — model evicted from VRAM" if snapshot.model_unloaded else "")
    )

    if conditions:
        readable = ", ".join(c.replace("_", " ") for c in conditions)
        lines.append(f"- **Watching** {readable}")
        spoken.append(f"I am currently watching {readable}.")
    else:
        spoken.append("Nothing needs your attention.")

    screen_text = f"{greeting}\n\n" + "\n".join(lines)
    return {"text": screen_text, "spoken": " ".join(spoken)}
